version: "3.1"
services:

  mysql:
    image: mysql:8.0
    container_name: website-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/mysql/mysql-overrides.cnf:/etc/mysql/conf.d/mysql-overrides.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=website
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"

  webserver:
    image: nginx:alpine
    container_name: website-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8089:80"

  php-fpm:
    build: docker/php-fpm
    container_name: website-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
